const products = [
    {
        prod_name: 'Minifigures',
        prod_image: 'img/prod1-1.png',
        prod_price: 4.99,
        prod_category: 'lego',
    },
    {
        prod_name: 'Batmobile',
        prod_image: 'img/prod1-2.jpeg',
        prod_price: 59.99,
        prod_category: 'lego',
    },
    {
        prod_name: 'Star Wars Boba Fett',
        prod_image: 'img/prod1-3.png',
        prod_price: 159.00,
        prod_category: 'lego',
    },
    {
        prod_name: 'Minecraft The Fox',
        prod_image: 'img/prod1-4.png',
        prod_price: 29.99,
        prod_category: 'lego',
    },
    {
        prod_name: 'Creator Space',
        prod_image: 'img/prod1-5.jpeg',
        prod_price: 24.99,
        prod_category: 'lego',
    },
    {
        prod_name: 'Super Mario',
        prod_image: 'img/prod1-6.jpeg',
        prod_price: 89.00,
        prod_category: 'lego',
    },
    {
        prod_name: 'Hot Wheels 5 Pack',
        prod_image: 'img/prod2-1.jpeg',
        prod_price: 10.00,
        prod_category: 'vehicles',
    },
    {
        prod_name: 'Hot Wheels Color',
        prod_image: 'img/prod2-2.jpeg',
        prod_price: 12.00,
        prod_category: 'vehicles',
    },
    {
        prod_name: 'Wreck Royale',
        prod_image: 'img/prod2-3.jpeg',
        prod_price: 12.50,
        prod_category: 'vehicles',
    },
    {
        prod_name: 'Monster Jam Freestyle',
        prod_image: 'img/prod2-4.jpeg',
        prod_price: 89.00,
        prod_category: 'vehicles',
    },
    {
        prod_name: 'WONDER City Train',
        prod_image: 'img/prod2-5.jpeg',
        prod_price: 199.99,
        prod_category: 'vehicles',
    },
    {
        prod_name: 'Hot Wheels Boulevard',
        prod_image: 'img/prod2-6.jpeg',
        prod_price: 7.99,
        prod_category: 'vehicles',
    },
    {
        prod_name: 'Malibu Barbie Gift Set',
        prod_image: 'img/prod3-1.jpeg',
        prod_price: 80.00,
        prod_category: 'dolls',
    },
    {
        prod_name: 'Barbie Playset',
        prod_image: 'img/prod3-2.jpeg',
        prod_price: 89.00,
        prod_category: 'dolls',
    },
    {
        prod_name: 'Barbie Fire Truck',
        prod_image: 'img/prod3-3.jpeg',
        prod_price: 89.00,
        prod_category: 'dolls',
    },
    {
        prod_name: 'Barbie Extra Minis Doll',
        prod_image: 'img/prod3-4.jpeg',
        prod_price: 16.00,
        prod_category: 'dolls',
    },
    {
        prod_name: 'Grill to Go Food Truck',
        prod_image: 'img/prod3-5.jpeg',
        prod_price: 207.00,
        prod_category: 'dolls',
    },
    {
        prod_name: 'Barbie Doll',
        prod_image: 'img/prod3-6.jpeg',
        prod_price: 20.00,
        prod_category: 'dolls',
    },
    {
        prod_name: 'Crayola Letters',
        prod_image: 'img/prod4-1.jpeg',
        prod_price: 29.00,
        prod_category: 'creativity',
    },
    {
        prod_name: 'Orbeez Grown Pack ',
        prod_image: 'img/prod4-2.jpeg',
        prod_price: 20.00,
        prod_category: 'creativity',
    },
    {
        prod_name: 'Jelli Rez Packs',
        prod_image: 'img/prod4-3.jpeg',
        prod_price: 8.00,
        prod_category: 'creativity',
    },
    {
        prod_name: 'Standing Art Easel',
        prod_image: 'img/prod4-4.jpeg',
        prod_price: 79.00,
        prod_category: 'creativity',
    },
    {
        prod_name: 'Cool Maker Nail Salon',
        prod_image: 'img/prod4-5.jpeg',
        prod_price: 35.00,
        prod_category: 'creativity',
    },
    {
        prod_name: 'Playdoh Super Pack',
        prod_image: 'img/prod4-6.jpeg',
        prod_price: 19.99,
        prod_category: 'creativity',
    },
];
